// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JptlTltBIzlX-D3utzXrifroaRySTNc',
    appId: '1:823688109763:android:1e736da329ac0ee07ccc76',
    messagingSenderId: '823688109763',
    projectId: 'tgwfinancesapp',
    databaseURL: 'https://tgwfinancesapp-default-rtdb.firebaseio.com',
    storageBucket: 'tgwfinancesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCII4zxXPixguFC5a8VxX6a14m0M8nWNyM',
    appId: '1:823688109763:ios:38f454d2d28063687ccc76',
    messagingSenderId: '823688109763',
    projectId: 'tgwfinancesapp',
    databaseURL: 'https://tgwfinancesapp-default-rtdb.firebaseio.com',
    storageBucket: 'tgwfinancesapp.appspot.com',
    iosClientId: '823688109763-8cm1o0j1e86hhljfd8kj2io9rb4j01re.apps.googleusercontent.com',
    iosBundleId: 'com.example.tgwFinanceApp',
  );
}
